name: Build and Deploy React App

on:
  push:
    branches:
      - deploy-FE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Create env file
        run: |
          touch ./client/.env
          echo "${{ secrets.VITE_SECRET }}" > ./client/.env

      - name: Build Project
        run: npm run build
        working-directory: ./client
  
  deploy:
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_NGINX_SG }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_NGINX_HOST }}
          port: 22
          username: ${{ secrets.EC2_NGINX_USERNAME }}
          key: ${{ secrets.EC2_NGINX_PRIVATE_KEY }}
          source: "./client/dist/*"
          target: "/usr/share/nginx/html"
          
      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_NGINX_SG }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32


