name: Build and Deploy React App

on:
  push:
    branches:
      - deploy-FE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change directory
        run: cd client

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: /home/runner/work/Team9-HexaCore/Team9-HexaCore/client

      - name: Build Project
        run: npm run build
        working-directory: /home/runner/work/Team9-HexaCore/Team9-HexaCore/client

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          working-directory: /home/runner/work/Team9-HexaCore/Team9-HexaCore/client
          branch: gh-pages
          folder: /
          token: ${{ secrets.PERSONAL_ACCESS_KEY }}

